/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as publicSearchRouteRouteImport } from './routes/(public)/search/route'
import { Route as publicCategoriesCategoryIdRouteRouteImport } from './routes/(public)/categories/$categoryId/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSearchRouteRoute = publicSearchRouteRouteImport.update({
  id: '/(public)/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const publicCategoriesCategoryIdRouteRoute =
  publicCategoriesCategoryIdRouteRouteImport.update({
    id: '/(public)/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof publicSearchRouteRoute
  '/categories/$categoryId': typeof publicCategoriesCategoryIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof publicSearchRouteRoute
  '/categories/$categoryId': typeof publicCategoriesCategoryIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(public)/search': typeof publicSearchRouteRoute
  '/(public)/categories/$categoryId': typeof publicCategoriesCategoryIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/search' | '/categories/$categoryId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/search' | '/categories/$categoryId'
  id: '__root__' | '/' | '/(public)/search' | '/(public)/categories/$categoryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  publicSearchRouteRoute: typeof publicSearchRouteRoute
  publicCategoriesCategoryIdRouteRoute: typeof publicCategoriesCategoryIdRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/search': {
      id: '/(public)/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof publicSearchRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/categories/$categoryId': {
      id: '/(public)/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof publicCategoriesCategoryIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  publicSearchRouteRoute: publicSearchRouteRoute,
  publicCategoriesCategoryIdRouteRoute: publicCategoriesCategoryIdRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
